SECRET_KEY = 'thisisantipoetry'
SQLALCHEMY_DATABASE_URI = 'postgresql:///microblog'
TESTING = False
MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USERNAME = ''  # FILL OUT
MAIL_PASSWORD = ''  # FILL OUT
MAIL_DEFAULT_SENDER = ('Blogette', 'naomitshapiro@gmail.com')
