"""empty message

Revision ID: 14f5ee244408
Revises: 14c0b493d336
Create Date: 2014-03-12 18:45:13.204750

"""

# revision identifiers, used by Alembic.
revision = '14f5ee244408'
down_revision = '14c0b493d336'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.add_column(u'post', sa.Column('author_id', sa.Integer(),
                                     sa.ForeignKey('author.id'), nullable=True)
                  )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'post', 'author_id')
    op.drop_table('author')
    ### end Alembic commands ###
